sudo: true
language: c
compiler:
    - gcc
os:
    - linux
before_install:
        - sudo apt-get install rpm
install:
        - mkdir ${HOME}/BUILD ${HOME}/BUILDROOT ${HOME}/RPMS ${HOME}/SOURCES ${HOME}/SPECS ${HOME}/SRPMS
        - cp pwrapi-ref-1.1.1.tgz ${HOME}/SOURCES
        - cp piapi-2.1.1.tgz ${HOME}/SOURCES
        - cp pwrapi-ref.spec ${HOME}/SPECS
        - cp piapi.spec ${HOME}/SPECS
        - cd ${HOME}/SPECS
        - sed -i.bak '/BuildRequires/d' pwrapi-ref.spec
        - sed -i.bak '/BuildRequires/d' piapi.spec
        - rpmbuild -v -ba pwrapi-ref.spec
        - rpmbuild -v -ba piapi.spec
script:
        - echo "NO NEED TO TEST TOOLS SINCE EACH REPO ALREADY DOES"
notifications:
    email:
        recipients:
            - ddeboni@sandia.gov
        on_success: [change]
        on_failure: [always] 
