sudo: true
language: c
compiler:
    - gcc
os:
    - linux
before_install:
        - sudo apt-get install rpm autotools-dev
install:
        - git clone https://github.com/pwrapi/release ${HOME}/release
        - mkdir ${HOME}/rpmbuild
        - cd ${HOME}/rpmbuild
        - mkdir BUILD BUILDROOT RPMS SOURCES SPECS SRPMS
        - cp ${HOME}/release/pwrapi-ref-1.1.1.tgz SOURCES
        - cp ${HOME}/release/piapi-2.1.1.tgz SOURCES
        - cp ${HOME}/release/pwrapi-ref.spec SPECS
        - cp ${HOME}/release/piapi.spec SPECS
        - cd ${HOME}/rpmbuild/SPECS
        - rpmbuild -v -ba pwrapi-ref.spec
        - rpmbuild -v -ba piapi.spec
script:
        - export POWERAPI_CONFIG=/usr/share/doc/pwrapi/examples/config/dummySystem.xml
        - export POWERAPI_ROOT=plat
        - pwrapi -a P -t P
        - piver
        - pinative -s 100 -f 100
notifications:
    email:
        recipients:
            - ddeboni@sandia.gov
        on_success: [change]
        on_failure: [always] 
