sudo: true
language: c
compiler:
    - gcc
os:
    - linux
before_install:
        - sudo apt-get install alien dpkg-dev debhelper build-essential
install:
        - git clone https://github.com/pwrapi/release
        - cd release
        - mkdir rpmbuild
        - cd rpmbuild
        - mkdir BUILD BUILDROOT RPMS SOURCES SPECS SRPMS
        - cp ../pwrapi-ref-1.1.1.tgz SOURCES
        - cp ../piapi-2.1.1.tgz SOURCES
        - cp ../pwrapi-ref.spec SPECS
        - cp ../piapi.spec SPECS
        - cd SPECS
        - sudo rpmbuild -v -ba pwrapi-ref.spec
        - sudo rpmbuild -v -ba piapi.spec
script:
        - export POWERAPI_CONFIG=/usr/share/doc/pwrapi/examples/config/dummySystem.xml
        - export POWERAPI_ROOT=plat
        - pwrapi -a P -t P
        - piver
        - pinative -s 100 -f 100
notifications:
    email:
        recipients:
            - ddeboni@sandia.gov
        on_success: [change]
        on_failure: [always] 
